# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoodList

    pod 'RxSwift','~> 4.0'
    pod 'RxCocoa','~> 4.0'

end
